version: '3.4'

services:
  leaguemanager.webapi:
    image: ${DOCKER_REGISTRY-}leaguemanagerwebapi
    build:
      context: .
      dockerfile: src/Presentation/LeagueManager.WebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  leaguemanager.league.database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=league
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    volumes:
      - ./.containers/season-db:/var/lib/posgresql/data
    ports:
     - 5432:5432
  leaguemanager.statistics.database:
    image: elasticsearch:8.13.4
    ports:
     - 9200:9200
    volumes:
      - ./.containers/archive-db:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  #leaguemanager.broker:
  #  image: rabbitmq:3.13-management
  #  ports: 
  #    - 5672:5672
  #    - 15672:15672 
  #  volumes:
  #   - ./.containers/broker:/var/lib/rabbitmq